Datastore Support
CarlosM10011/google-step2020 pull request #11
Opened 2020-06-09 21:23 UTC by CarlosM10011

This pull request adds datastore support for posted comments.

2020-06-10 16:39 UTC, tinagrasso requested changes

2020-06-10 16:39 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  private final Query query = new Query("Comment").addSort("created", SortDirection.DESCENDING);
Create constants for all strings!

2020-06-11 16:55 UTC, tinagrasso approved these changes

2020-06-15 17:51 UTC, hzimz approved these changes

2020-06-15 19:04 UTC, merged