Add java servlet to randomly generate fact
CarlosM10011/google-step2020 pull request #6
Opened 2020-06-03 17:00 UTC by CarlosM10011

This pull request adds the server side code for the random fact generator.

Partially addresses issue #5.

2020-06-04 14:51 UTC, tinagrasso requested changes

2020-06-04 14:51 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/RandomFactServlet.java
> +    response.setContentType("text/html;");
Make the string a class level constant.

```
private const String CONTENT_TYPE = "text/html";
```

2020-06-04 14:51 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/RandomFactServlet.java
> +    facts[2] = "The Summit supercomputer can reach up to 200 petaFLOPS.";
Prefer a List and make it an instance variabel.

```
private List<String> randomFacts = Lists.of("....", "....");
```

https://docs.oracle.com/javase/9/core/creating-immutable-lists-sets-and-maps.htm#JSCOR-GUID-202D195E-6E18-41F6-90C0-7423B2C9B381

2020-06-04 14:51 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/RandomFactServlet.java
> +    Random rand = new Random();
Make this an instance variable.

2020-06-04 16:18 UTC, hzimz approved these changes
LGTM once you address Tina's comments.

2020-06-05 15:35 UTC, tinagrasso requested changes

2020-06-05 15:35 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/RandomFactServlet.java
> +          });
Remove object arrays and make immutable.

```
private final List<String> facts = Collections.unmodifiableList(Arrays.asList("a", "b", "c"));
```

2020-06-05 16:31 UTC, tinagrasso requested changes

2020-06-05 16:31 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/RandomFactServlet.java
> +              new String[] {
Remove the object array. Please look at the javadoc for this method.
https://docs.oracle.com/javase/8/docs/api/index.html?java/util/List.html

2020-06-09 15:19 UTC, tinagrasso approved these changes

2020-06-09 17:26 UTC, merged