Use the fetch JS API to get random facts
CarlosM10011/google-step2020 pull request #7
Opened 2020-06-03 18:51 UTC by CarlosM10011

This pull request is the client side for issue #5, which is to migrate the fact generator to a java servlet.

closes #5

2020-06-03 19:46 UTC, hzimz requested changes

2020-06-03 19:46 UTC, hzimz commented on portfolio/src/main/webapp/script.js
> +  const fact = await response.text();
It's good practice to wrap this in a try-catch block to handle the await call failing.

2020-06-04 14:55 UTC, tinagrasso approved these changes
Please wait for Hussein's approval before merging.

2020-06-04 15:05 UTC, hzimz approved these changes

2020-06-04 15:13 UTC, hzimz requested changes

2020-06-04 15:13 UTC, hzimz commented on portfolio/src/main/webapp/script.js
> +    const response = await fetch('/random-fact');
Sorry, move the initial await outside the try-catch block

2020-06-08 20:04 UTC, hzimz approved these changes

2020-06-08 21:22 UTC, merged