Add server side code for posting comments
CarlosM10011/google-step2020 pull request #9
Opened 2020-06-08 17:26 UTC by CarlosM10011

This pull request adds the server side code for posting comments on the server.

2020-06-10 16:31 UTC, tinagrasso requested changes

2020-06-10 16:31 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    String body = request.getParameter("body");
Create constants for these strings.

2020-06-10 16:31 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    if (name == null || body == null) { // Someone sending a bad form.
What about empty strings?

2020-06-11 16:41 UTC, tinagrasso requested changes

2020-06-11 16:41 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    if (!isSaneForm(name, body)) {
Consider adding an error response code and message. 4XX errors are for client errors.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2020-06-11 16:41 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    final String body = request.getParameter("body");
Constants for param fields.

2020-06-15 14:17 UTC, tinagrasso requested changes

2020-06-15 14:17 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        && (body != null && !body.isEmpty())) { // Someone sending a bad form.
You can simply return the if statement.

```
return (name != null && !name.isEmpty()) && (body != null && !body.isEmpty());
```

2020-06-15 17:23 UTC, hzimz approved these changes

2020-06-15 17:28 UTC, tinagrasso requested changes

2020-06-15 17:28 UTC, tinagrasso commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      response.sendError(HttpServletResponse.SC_BAD_REQUEST);
Error message?

2020-06-15 18:36 UTC, tinagrasso approved these changes

2020-06-15 18:57 UTC, merged